version: '3.8'
services:

  php:
    container_name: php
    restart: unless-stopped
    build:
      context: .
      target: app_php
      args:
        - APP_ENV=dev
        - APP_DIR=.
        - PHP_CONF_DIR=./.docker/php
        - ENTRYPOINT_FILE=docker-entrypoint.sh
        - GID=1000
        - UID=1000
        - INSTALL_DIR=app
        - PHP_VERSION=8.2
        - TZ=Europe/Paris
    environment:
      - APP_ENV=dev
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      test: ./usr/local/bin/docker-healthcheck
    volumes:
      - ".:/srv/app:rw"
      - "./var/log:/srv/app/var/log:rw"
      - "./.docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro"

  redis:
    image: redislabs/redistimeseries
    ports:
      - "6379"