version: "3.4"
services:

  app_price_request:
    container_name: app_price_request
    restart: unless-stopped
    build:
      context: .
      target: app_php
      args:
        - APP_ENV=dev
        - APP_DIR=.
        - PHP_CONF_DIR=./.docker/php
        - ENTRYPOINT_FILE=docker-entrypoint.sh
        - GID=1000
        - UID=1000
        - INSTALL_DIR=app
        - PHP_VERSION=8.2
        - TZ=Europe/Paris
    networks:
      - tradebot

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tradebot


  redis:
    image: redislabs/redistimeseries
    ports:
      - "6379"
    networks:
      - tradebot

networks:
  tradebot:
    external: true