version: "3.4"

# Development environment override
services:
  app:
    build:
      context: .
      target: app_php
    environment:
      APP_ENV: dev
      XDEBUG_MODE: "${XDEBUG_MODE:-off}" # See https://xdebug.org/docs/all_settings#mode
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    volumes:
      - ".:/srv/app"
      - "./var/log:/srv/app/var/log:rw"
      - "./.docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro"