parameters:
    downloadDir: 'var/data/download'
    backupFolder: 'var/data/download/backup'
    redisHost: '%env(string:REDIS_HOST)%'
    bybitApiKeys:
        ApiKey: '%env(string:BYBIT_API_KEY)%'
        Secret: '%env(string:BYBIT_API_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Functionnal\:
        resource: '../tests/Functionnal/*'

    # this config only applies to the services created by this file
    _instanceof:
        App\Domain\DataProcessor\SampleChecker:
            tags: ['app.sample_checker']

    App\Infra\DataProcessor\SampleCheckerRegistry:
        - arguments:
            !tagged_iterator app.sample_checker
